apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: echo-dev
  namespace: default
  annotations:
    fluxcd.io/automated: "true"
    filter.fluxcd.io/chart-image: glob:echo*
spec:
  releaseName: echo-dev
  chart:
    git: git@github.com:imeilon/helm-operator-get-started
    path: charts/echo
    ref: master
  values:
    image:
      repository: weirdocker/echo
      tag: echo5
    replicaCount: 1
    hpa:
      enabled: false
