apiVersion: v1
kind: Secret
metadata:
  name: secret
type: Opaque
stringData:
  MONGODBURL: 'mongodb://eilon:eilon@mongo-mongodb-0.mongo-mongodb-headless:27017,mongo-mongodb-1.mongo-mongodb-headless:27017,mongo-mongodb-2.mongo-mongodb-headless:27017/eilon'
