apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: letsencrypt-prod
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: eilon696@gmail.com
    privateKeySecretRef:
      name: eilon-key-prod
    solvers:
    - http01:
       ingress:
         class: nginx

